<?php 
define('CNF_APPNAME','Navizon');
define('CNF_APPDESC','Navizon');
define('CNF_COMNAME','Navizon');
define('CNF_EMAIL','info@mail.com');
define('CNF_METAKEY','Navizon');
define('CNF_METADESC','Navizon');
define('CNF_GROUP','3');
define('CNF_ACTIVATION','confirmation');
define('CNF_MULTILANG','1');
define('CNF_LANG','en');
define('CNF_REGIST','false');
define('CNF_FRONT','false');
define('CNF_RECAPTCHA','false');
define('CNF_THEME','sximone');
define('CNF_RECAPTCHAPUBLICKEY','');
define('CNF_RECAPTCHAPRIVATEKEY','');
define('CNF_MODE','production');
define('CNF_LOGO','backend-logo.png');
define('CNF_ALLOWIP','');
define('CNF_RESTRICIP','192.116.134 , 194.111.606.21 ');
?>